# Generated by Django 3.2.9 on 2021-12-08 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bangalorejobs',
            new_name='Bangalorejob',
        ),
        migrations.RenameModel(
            old_name='chennaijobs',
            new_name='Chennaijob',
        ),
        migrations.RenameModel(
            old_name='hydjobs',
            new_name='Hydjob',
        ),
        migrations.RenameModel(
            old_name='punejobs',
            new_name='Punejob',
        ),
    ]
